function build_1dof_simulink_model()
%BUILD_1DOF_SIMULINK_MODEL Generate a Simulink closed-loop model.
%
% This script is a portable fallback for environments where the Simulink MCP
% model_edit tool is not available. Run it inside MATLAB with Simulink.

model = 'one_dof_copter_pso_pid';
if bdIsLoaded(model)
    close_system(model, 0);
end

new_system(model);
open_system(model);

add_block('simulink/Sources/Constant', [model '/Reference_deg'], ...
    'Value', 'p.refDeg', 'Position', [40 80 130 110]);
add_block('simulink/User-Defined Functions/MATLAB Function', [model '/PID_and_Plant'], ...
    'Position', [210 55 430 165]);
add_block('simulink/Sinks/Scope', [model '/Scope'], ...
    'Position', [530 55 560 165]);
add_block('simulink/Sinks/To Workspace', [model '/theta_deg'], ...
    'VariableName', 'theta_deg', 'SaveFormat', 'StructureWithTime', ...
    'Position', [520 195 610 225]);

add_line(model, 'Reference_deg/1', 'PID_and_Plant/1', 'autorouting', 'on');
add_line(model, 'PID_and_Plant/1', 'Scope/1', 'autorouting', 'on');
add_line(model, 'PID_and_Plant/1', 'theta_deg/1', 'autorouting', 'on');

block = [model '/PID_and_Plant'];
code = sprintf([ ...
    'function theta_deg = fcn(ref_deg)\\n', ...
    '%%#codegen\\n', ...
    'persistent x gains p initialized\\n', ...
    'if isempty(initialized)\\n', ...
    '    p = init_1dof_params();\\n', ...
    '    if exist(''output/tuned_pid_gains.mat'', ''file'')\\n', ...
    '        s = load(''output/tuned_pid_gains.mat'', ''gains'');\\n', ...
    '        gains = s.gains;\\n', ...
    '    else\\n', ...
    '        gains = struct(''Kp'', 20, ''Ki'', 5, ''Kd'', 2);\\n', ...
    '    end\\n', ...
    '    p.refDeg = ref_deg;\\n', ...
    '    x = zeros(6,1);\\n', ...
    '    x(3) = pwm_to_omega(p.hoverPwm, p);\\n', ...
    '    x(4) = pwm_to_omega(p.hoverPwm, p);\\n', ...
    '    initialized = true;\\n', ...
    'end\\n', ...
    'p.refDeg = ref_deg;\\n', ...
    '[dx, ~] = one_dof_closed_loop_ode(0, x, gains, p);\\n', ...
    'x = x + p.Ts * dx;\\n', ...
    'theta_deg = x(1) * 180 / pi;\\n', ...
    'end\\n']);

set_param(block, 'Script', code);
set_param(model, 'StopTime', '6');
set_param(model, 'FixedStep', '0.01');
set_param(model, 'Solver', 'FixedStepDiscrete');

save_system(model, fullfile(pwd, [model '.slx']));
fprintf('Created %s.slx\n', model);
end
